### ISSUE TITLE
doesnt show modal with react-navigation

### ISSUE THREAD

**Issue by TestTitans** [raynor85/react-native-modal-wrapper#1]
doesnt show modal with react-navigation and some times show make a blink

**Comment by raynor85** [comment]
Thank you for the feedback.
Can you please show or send me the code?
Also try to set the isNative prop to false, and see if this helps.

**Comment by TestTitans** [comment]
showOverlay={false}
isNative={false}
solve problem Thanks man.

**Comment by raynor85** [comment]
Feel free to update the plugin to the last version as I made some
improvements that allow the user to customise more the modalWrapper content
when isNative={false}.

Thank you for using the plugin, any other feedbacks are appreciated.

Ruben
