### ISSUE TITLE
Modal visible at bottom of screen?

### ISSUE THREAD

**Issue by GollyJer** [raynor85/react-native-modal-wrapper#12]
Hi.  And thanks for the awesome component!  I've been using it successfully on many screens of my app.

Today however I've run into an issue I can't figure out.
When I add a modal to my component a white/grey section appears at the bottom of the screen.
![72915](https://user-images.githubusercontent.com/689204/36211268-c800df48-116e-11e8-8ae9-6c53b7a751f8.jpg)

Is there something simple I may be doing wrong?

Thanks!
Jeremy

**Comment by raynor85** [comment]
It's hard to tell and I don't think it is necessarily related to the modal component. Have you tried to inspect that element? You can use https://facebook.github.io/react-native/docs/debugging.html as reference. I suggest you using react-devtools to inspect the element using the simulator.

**Comment by raynor85** [comment]
I'm closing it due to inactivity and because it doesn't really seem related to the modal itself. Feel free to keep posting here and I'll try to help you.

**Comment by GollyJer** [comment]
Thanks for the help @raynor85. It's definitely related.  If I comment out the one line of code with the modal the white area goes away.  However, I didn't want to reach out until I followed you first advice about inspecting the element. Which is proving difficult because I'm using Expo.

I'll reach out again if I hit a wall. Thanks!

**Comment by raynor85** [comment]
I discourage using Expo, it's too limited. You can always copy the project
and eject it. Are you using isNative={true}? Try to paste your screen
component code, maybe I can try to replicate it.

**Comment by GollyJer** [comment]
Hey... just wanted to follow up on this in case someone finds it in search.  

I was accidentally using flex and margin on the modal's style prop.  This was pushing up the screen from the bottom.  Removing the style corrected the problem.
