### ISSUE TITLE
style={styles.sidebar} ?

### ISSUE THREAD

**Issue by sinclas** [raynor85/react-native-modal-wrapper#13]
Hi,

Your example shows this style reference: style={styles.sidebar}
Can you show the style settings for the referenced style class?  Trying to get the sidebar's width to be wider as it looks in your example.  How can you set width?

Thanks
S

**Comment by raynor85** [comment]
style is applied to the inner component, so to achieve that you have to play with both `containerStyle` and `style`. Those properties are merged with the following default styles:
```js
  container: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center'
  },
  modal: {
    backgroundColor: '#fff',
    justifyContent: 'center'
  },
```
