### ISSUE TITLE
Keyboard Spacer and isNative={false}

### ISSUE THREAD

**Issue by samcolby** [raynor85/react-native-modal-wrapper#7]
Hi, 

Any thoughts on how to get this to work?  

I really need to use isNative={false} as I don't want the modal overlay to take up the whole screen on iPads.  

Thanks
Sam

**Comment by raynor85** [comment]
Well, first of all, what do you want to achieve? The native modal component fills the entire space by default and there is no way to change this behaviour. If you want to remove the overlay, there is a property that do that, but if you want to limit the visibility of the modal to a portion of the screen, you can play with containerStyle and isNative={false}. Try for example to pass this object to the containerStyle, something like { top: 100, left: 100 }, you should be able to limit the modal boundaries changing its absolute positioning

**Comment by samcolby** [comment]
Hi,

Sorry, I really didn't explain that very well. 

I was poking around the code trying to get the keyboardspacer to work with the js solution and saw that it was explicitly removed with the {isJs && keyboardspacer} line. Was wondering if you had any thoughts on how to fix it. 

As for what I'm trying to achieve. On iPads I'm using something similar to this https://blog.typework.com/react-native-universal/ to approximate a split screen app.  Which works well, except for popups. I'd like to limit them to either side of the split screen, rather than covering both sides. 

This nice little component is one of the few that will do this, but unfortunately the keyboard spacer doesn't work.

Thanks for response

**Comment by raynor85** [comment]
This is actually an issue of react native with the iPad, as it is mentioned
in the readme file: https://github.com/facebook/react-native/issues/7340.
To overcome this, you can pass a property called screenHeight and compute
the screen height by yourself.

**Comment by samcolby** [comment]
Yes, I saw that, but that only works when isNative={true} . Which is full screen. 

The keyboardspacer doesn't work if isNative={false} on an iPad or phone.

**Comment by raynor85** [comment]
Keyboardspacer doesn't work on iPads for the react native bug mentioned
above, and only when you rotate your device, but on iPhones it works fine.
The problem you are facing is different, and I assure you the positioning
is working fine. Please tell me which version of react native you are
using, post your code and provide a screenshot.

**Comment by samcolby** [comment]
Hi, I'm on my phone at the moment so can't. I'll try later today or maybe tomorrow now.  

I'm pretty sure that it doesn't get applied though. 

You have this line in renderContainer which stops it from being added if native={false} 

 {isJs && keyboardSpacer}

Code to follow soonish. Thanks for help on this !

**Comment by samcolby** [comment]
Hi, 

You're completely right.  It turns out I had some flexbox issues with the way I was trying to do that yesterday.  

I'm really sorry for the confusion.  That will teach me to reply on my phone!  

Great little library btw.

Thanks
Sam

**Comment by raynor85** [comment]
No problem, any feedbacks are always welcomed. Enjoy!
